#spring:
# application:
#    name: covid19-watchlist
# data:
#   mongodb:
#     database: coviddb
#     port: 27017
#     host: localhost
# 
#server:
# port: 8082
# 
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true

#spring:autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration 