server:
  port: 9000

  # api gateway config for routing and load balancing

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    
  instance:
    hostname: localhost
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: covid19
        uri: lb://covid19
        predicates:
        - Path=/api/v1/auth/**
      - id: covid19-watchlist
        uri: lb://covid19-watchlist
        predicates:
        - Path=/api/v1/watchlist/**
          